### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by xnacly** [xNaCly/better-issues#3]
## High priority
- [ ] catch empty body issue: http://localhost:3000/render_issue?issue=https://github.com/fosscord/fosscord-landingpage/issues/42 
- [ ] rewrite project in ts and modularize 
- [ ] rework documentation / README
- [ ] switch to svg rendering to decrease latency for each request
- [ ] redeploy to other provider (not heroku)

## Low priority
- [x] since heroku uses linux, add `segoe-ui` from external source (or fs) to fix the styling
- [ ] only render markdown for README's if the fileending is .md
- [ ] auto extract README from linked repo#
- [ ] add themes (dark/high-contrast)
